### ISSUE TITLE
Shell Script not working

### ISSUE THREAD

**Issue by karthiks2611** [kinshukdua/FedUKD#1]
```sh getAllData.sh```

 Not working

**Comment by kinshukdua** [comment]
The drive is private, while we change the links, please download and extract both the dataset from their respective links-
Cityscape: https://www.cityscapes-dataset.com/
Chennai Land Use: https://github.com/simonelias128/Chennai-Land-Use-Dataset/

**Comment by karthiks2611** [comment]
Thanks!
